install.packages("rJava", repos = "http://cran.us.r-project.org")
install.packages("chron", repos = "http://cran.us.r-project.org")
install.packages("lattice", repos = "http://cran.us.r-project.org")
install.packages("mclust", repos = "http://cran.us.r-project.org")
install.packages("rMR", repos = "http://cran.us.r-project.org")
install.packages("respirometry", repos = "http://cran.us.r-project.org")
